<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression Methods Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Garcia-Vuksic-RMProject-2024_files/libs/clipboard/clipboard.min.js"></script>
<script src="Garcia-Vuksic-RMProject-2024_files/libs/quarto-html/quarto.js"></script>
<script src="Garcia-Vuksic-RMProject-2024_files/libs/quarto-html/popper.min.js"></script>
<script src="Garcia-Vuksic-RMProject-2024_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Garcia-Vuksic-RMProject-2024_files/libs/quarto-html/anchor.min.js"></script>
<link href="Garcia-Vuksic-RMProject-2024_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Garcia-Vuksic-RMProject-2024_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Garcia-Vuksic-RMProject-2024_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Garcia-Vuksic-RMProject-2024_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Garcia-Vuksic-RMProject-2024_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
</head><body class="fullcontent">\usepackage{xcolor}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{bm}

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>





<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression Methods Project</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction-and-exploratory-data-analysis" class="level4">
<h4 class="anchored" data-anchor-id="introduction-and-exploratory-data-analysis"><strong>1. Introduction and Exploratory Data Analysis</strong></h4>
<p>A recent paper (winner of the 2024 IgNobel Prize in Probability) analyzed over 350,000 coin flips to investigate the phenomenon that a coin starting heads-up tends to land heads-up with a probability slightly above 0.5, around 0.51, and similarly for tails-up. While the original paper adopted a Bayesian framework, our goal here is to employ frequentist regression methods to explore this possible bias and the factors that might influence it—such as participant-specific flipping techniques, coin characteristics, and the coin’s starting orientation.</p>
<ul>
<li><p><strong>State Objectives:</strong></p>
<ul>
<li>Clearly define the aims of your analysis.</li>
</ul></li>
<li><p><strong>Outline:</strong></p>
<ul>
<li>Provide a roadmap of your report’s structure.</li>
</ul></li>
</ul>
<p><strong>Data Description</strong></p>
<p>The dataset (in <code>data-agg.csv</code>) contains aggregated results from an experiment involving 48 participants flipping 211 different coins. Each row corresponds to the outcomes of flipping a <em>specific coin</em> by a <em>single participant</em> under two starting orientations: heads-up and tails-up. The columns are:</p>
<ul>
<li><p><strong>heads_heads</strong>: Number of flips that started heads-up and ended heads-up.</p></li>
<li><p><strong>tails_heads</strong>: Number of flips that started tails-up and ended heads-up.</p></li>
<li><p><strong>N_start_heads_up</strong>: Total flips that started heads-up.</p></li>
<li><p><strong>N_start_tails_up</strong>: Total flips that started tails-up.</p></li>
<li><p><strong>person</strong>: Participant identifier.</p></li>
<li><p><strong>coin</strong>: Coin identifier.</p></li>
</ul>
<p>We define for each row:</p>
<ul>
<li>$ = N_{} - $</li>
<li>$ = N_{} - $</li>
<li>$ = $</li>
</ul>
<p>The overall interest lies in the extent to which <span class="math inline">\(\text{prob_same_side}\)</span> exceeds 0.50, and whether this bias depends on the participant, coin, or starting orientation. Our analysis begins with studying the patterns in the data to inform modeling.</p>
<div class="cell">

</div>
<p><strong>Overall Probability of Landing on the Same Side</strong></p>
<p>To assess the overall bias, we first compute how often the coin ends on the same side it started.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  mean_prob_same_side median_prob_same_side sd_prob_same_side
                &lt;dbl&gt;                 &lt;dbl&gt;             &lt;dbl&gt;
1               0.508                 0.506            0.0235</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  df$prob_same_side
t = 5.0947, df = 210, p-value = 7.765e-07
alternative hypothesis: true mean is not equal to 0.5
95 percent confidence interval:
 0.5050585 0.5114438
sample estimates:
mean of x 
0.5082511 </code></pre>
</div>
</div>
<p>From these results, we find a <strong>mean probability</strong> of about 0.508, slightly exceeding 0.5. A one-sample t-test against 0.5 indicates a statistically significant difference <span class="math inline">\((p&lt; 0.05)\)</span>. Although the magnitude of this effect is small, it suggests a bias toward coins landing on the same side they started.</p>
<p>We visualize the distribution of these probabilities in Figure 1.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Garcia-Vuksic-RMProject-2024_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Figure 1: Histogram of the probability of landing on the same side across all coins and participants.</em></p>
<p>Most probabilities cluster around 0.5, but the distribution leans slightly to the right, reflecting the small bias observed. A few outliers exceed 0.6, which we will explore further.</p>
<p><strong>Participant-Level Analysis</strong></p>
<p>Next, we examine how this probability varies by participant. Differences in flipping technique or style could drive variation at the individual level.</p>
<p>We sum heads-up and tails-up flips by participant to obtain</p>
<p>$ p_i = $</p>
<p>where <span class="math inline">\((\text{heads_heads})_i\)</span> is the total number of heads outcomes from heads-up starts for participant <span class="math inline">\(i\)</span>, etc.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  mean_prob median_prob sd_prob
      &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;
1     0.510       0.505  0.0192</code></pre>
</div>
</div>
<p>The <strong>mean participant-level probability</strong> is around 0.510, slightly higher than the overall mean. This minor increase above the grand mean suggests participants differ in their flipping styles, possibly through differences in technique or consistency. This is illustrated in Figure 2.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Garcia-Vuksic-RMProject-2024_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Figure 2: Histogram of Probability of Landing on the Same Side by Participant</em></p>
<p>Although many participants cluster near 0.5, there are some notable outliers, reinforcing the notion that <strong>participant-specific effects</strong> could be important in modeling. We identify outliers by checking which participants’ probabilities lie beyond two standard deviations from the mean.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 8
  person     total_heads_heads total_tails_tails total_heads_up total_tails_up
  &lt;fct&gt;                  &lt;dbl&gt;             &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
1 JanYang                  510               446            877            814
2 TianqiPeng               780               902           1341           1459
# ℹ 3 more variables: total_same_side &lt;dbl&gt;, total_flips &lt;dbl&gt;,
#   prob_same_side &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Coin-Level Analysis</strong></p>
<p>We then group flips by each <em>coin</em> to see whether some coins inherently land on the same side more frequently. Analogously, we compute</p>
<p><span class="math inline">\(q_j = \frac{(\text{heads_heads})_j + (\text{tails_tails})_j}{(\text{total_flips})_j}\)</span></p>
<p>where <span class="math inline">\((\text{heads_heads})_j\)</span> denotes the total number of heads outcomes from heads-up starts for coin $j$, etc.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  mean_prob median_prob sd_prob
      &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;
1     0.504       0.506  0.0135</code></pre>
</div>
</div>
<p>The <strong>mean coin-level probability</strong> is about 0.504, with smaller overall variability compared to participants, as shown in Figure 3.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Garcia-Vuksic-RMProject-2024_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Figure 3: Histogram of the probability of landing on the same side by coin.</em></p>
<p>Coin-level probabilities remain tightly grouped around 0.5. This finding indicates that, <strong>on average</strong>, coin characteristics may not strongly affect the outcome, at least not to the same extent as participant-specific effects. Outliers were identified for coins with probabilities exceeding two standard deviations from the mean.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 8
  coin    total_heads_heads total_tails_tails total_heads_up total_tails_up
  &lt;fct&gt;               &lt;dbl&gt;             &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
1 0.01GBP               235               240            497            503
2 0.02EUR                78                63            157            143
3 0.50SGD               808               688           1452           1329
4 1MXN                 2215              2292           4177           4257
# ℹ 3 more variables: total_same_side &lt;dbl&gt;, total_flips &lt;dbl&gt;,
#   prob_same_side &lt;dbl&gt;</code></pre>
</div>
</div>
<p>To further investigate, we analyzed person/coin combinations to explore whether specific participant-coin interactions exhibit unusual outcomes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate probabilities for person/coin combinations</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>person_coin_probs <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(person, coin) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">prob_same_side =</span> <span class="fu">mean</span>(prob_same_side, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify person/coin combination outliers</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>person_coin_outliers <span class="ot">&lt;-</span> person_coin_probs <span class="sc">%&gt;%</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(prob_same_side <span class="sc">&gt;</span> <span class="fu">mean</span>(prob_same_side) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sd</span>(prob_same_side) <span class="sc">|</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>           prob_same_side <span class="sc">&lt;</span> <span class="fu">mean</span>(prob_same_side) <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sd</span>(prob_same_side))</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(person_coin_outliers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 3
  person          coin    prob_same_side
  &lt;fct&gt;           &lt;fct&gt;            &lt;dbl&gt;
1 FranziskaAssion 1EUR             0.557
2 JanYang         0.50EUR          0.604
3 JasonNak        0.50EUR          0.46 
4 MagdaMatetovici 1CAD             0.62 
5 TianqiPeng      0.20EUR          0.621
6 TianqiPeng      0.50EUR          0.604
7 TianqiPeng      1EUR             0.574
8 XiaochangZhao   0.50SGD          0.571
9 XiaoyiLin       0.50EUR          0.446</code></pre>
</div>
</div>
<p>TianqiPeng and JanYang were identified as outlier participants.</p>
<p>**maybe say something else??? lol im tired and not so sure**</p>
<p><strong>Effect of Starting Side</strong></p>
<p>Finally, we explore whether starting the coin heads-up vs.&nbsp;tails-up alters the likelihood of ending on the same side. We compare:</p>
<ul>
<li><p><span class="math inline">\(p_{11}=P(Heads→Heads)\)</span></p></li>
<li><p><span class="math inline">\(p_{00}=P(Tails→Tails)\)</span></p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  mean_prob_heads_to_heads mean_prob_tails_to_tails sd_prob_heads_to_heads
                     &lt;dbl&gt;                    &lt;dbl&gt;                  &lt;dbl&gt;
1                    0.508                    0.508                 0.0257
# ℹ 1 more variable: sd_prob_tails_to_tails &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The results indicate <strong>both</strong> heads-up and tails-up flips have a mean probability of about 0.508 of landing on the same side. A t-test reveals no significant difference between the two groups, implying that “heads-up” vs.&nbsp;“tails-up” starts do not systematically alter the bias once participant and coin factors are averaged out.</p>
<p>ive been thinking of how davison said hypothesis tests are overused is this one of those cases? or is it a reasonable test? i think so but im also overthinking</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  starting_side mean_prob sd_prob
  &lt;chr&gt;             &lt;dbl&gt;   &lt;dbl&gt;
1 Heads Up          0.508  0.0257
2 Tails Up          0.508  0.0299</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  probability by starting_side
t = 0.091768, df = 410.93, p-value = 0.9269
alternative hypothesis: true difference in means between group Heads Up and group Tails Up is not equal to 0
95 percent confidence interval:
 -0.005086409  0.005584567
sample estimates:
mean in group Heads Up mean in group Tails Up 
             0.5079109              0.5076618 </code></pre>
</div>
</div>
<p>A violin plot (Figure 4) shows the distribution of these probabilities:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Garcia-Vuksic-RMProject-2024_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Figure 4: Violin plot of the probability of landing on the same side by starting side.</em></p>
<p>Both distributions are centered around 0.508, with comparable spread, suggesting <strong>no notable systematic difference</strong> between starting heads-up or tails-up. Some outliers in each group do appear, which may reflect unique participant behaviors or chance fluctuations.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 2
# Groups:   starting_side [2]
   starting_side probability
   &lt;chr&gt;               &lt;dbl&gt;
 1 Heads Up            0.446
 2 Heads Up            0.570
 3 Tails Up            0.441
 4 Tails Up            0.602
 5 Tails Up            0.575
 6 Heads Up            0.615
 7 Tails Up            0.593
 8 Heads Up            0.604
 9 Tails Up            0.635
10 Heads Up            0.585
# ℹ 11 more rows</code></pre>
</div>
</div>
<p><strong>Summary of EDA Findings</strong></p>
<ul>
<li><p><strong>Slight Overall Bias</strong>: The mean probability of landing on the same side is 0.508, slightly above 0.5, indicating a modest but statistically significant bias.</p></li>
<li><p><strong>Participant Variability</strong>: A higher mean (0.510) and greater spread among participants highlight the importance of participant-specific effects. The outliers indicate certain participants might be flipping coins in a non-random manner.</p></li>
<li><p><strong>Minimal Coin Influence</strong>: Coin-level probabilities are tightly clustered around 0.5, suggesting coin characteristics may not play a major role ompared to participant influences —at least in this aggregated dataset.</p></li>
<li><p><strong>Starting Side</strong>: Heads-up or tails-up leads to virtually the same probability (0.508), indicating little difference in bias by orientation.</p></li>
</ul>
<p>These observations will guide the model-building phase. In particular, <strong>participant effects</strong> seem important, whereas coin effects appear weaker. Although starting side does not show a strong effect overall, we may still retain it in our models to capture any subtle differences.</p>
</section>
<section id="analysis" class="level4">
<h4 class="anchored" data-anchor-id="analysis"><strong>3. Analysis</strong></h4>
<p>Building upon the insights from our EDA, we proceed to model the probability of a coin landing on the same side using generalized linear models (GLMs). Given the binary nature of the outcome (landing on the same side or not), logistic regression is an appropriate choice. We begin with a simple model and later incorporate hierarchical structures to account for variability.</p>
<section id="simple-logistic-regression-model" class="level5">
<h5 class="anchored" data-anchor-id="simple-logistic-regression-model">Simple Logistic Regression Model</h5>
<p>As a first step, we fit the simplest possible logistic model, treating <strong>all flips</strong> (aggregated in <code>df</code>) as independent Bernoulli trials with a single intercept term. Conceptually, this model estimates a single probability $p$ that a flip lands heads, irrespective of participant or coin. Though extremely simplistic, it provides a baseline for more complex models.</p>
<p>Let <span class="math inline">\(Y\_{ij}\)</span> denote the number of same-side outcomes for the <span class="math inline">\(i\)</span>-th participant-coin pair under starting orientation <span class="math inline">\(j\)</span>, and let <span class="math inline">\(m_{ij}\)</span> represent the total flips under these conditions. A simple logistic regression assumes: <span class="math inline">\(\text{logit}\bigl(P(Y_{ij} = 1)\bigr) = \beta_0\)</span> where <span class="math inline">\(\beta_0 \in \mathbb{R}\)</span> is the log-odds of landing on the same side, irrespective of participant, coin, or starting orientation. The likelihood for <span class="math inline">\(\beta_0\)</span> is: $ L(<em>0) = ^{Y</em>{ij}} (1 - )^{m_{ij} - Y_{ij}}$ where <span class="math inline">\(\pi = \frac{\exp(\beta_0)}{1 + \exp(\beta_0)}\)</span>. The maximum likelihood estimate $<em>0$ is obtained by solving $ </em>{<em>0} </em>{i,j} Y_{ij} () + (m_{ij} - Y_{ij}) (1 - )$</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(heads_heads, N_start_heads_up - heads_heads) ~ 
    1, family = binomial, data = df)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) 0.031366   0.004783   6.558 5.44e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 284.28  on 210  degrees of freedom
Residual deviance: 284.28  on 210  degrees of freedom
AIC: 1739.6

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<div class="cell">

</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>